<a href="https://colab.research.google.com/github/pillaiganesh/MyAIAdventures/blob/main/Tensor%26Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import keras

Tensor - 0(Constanr, 1D (Vectors), 2D (Marix), 3D or More (Tensors)

In [2]:
const_1 =tf.constant(100)

In [3]:
const_1.shape

TensorShape([])

In [4]:
const_1.numpy()

100

In [5]:
const_2 = tf.constant([10,20,30,40,50,60,70,80])

In [6]:
const_2.shape

TensorShape([8])

In [7]:
const_2.numpy()

array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int32)

In [16]:
const_3 = tf.constant([[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]])

In [11]:
const_3.shape

TensorShape([3, 7])

In [12]:
const_3.numpy()

array([[10, 20, 30, 40, 50, 60, 70],
       [10, 20, 30, 40, 50, 60, 70],
       [10, 20, 30, 40, 50, 60, 70]], dtype=int32)

In [18]:
const_4 = tf.constant([
                      [[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]],

                      [[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]],
                       ])

In [19]:
const_4.shape

TensorShape([2, 3, 7])

In [20]:
const_4.numpy()

array([[[10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70]],

       [[10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70]]], dtype=int32)