<a href="https://colab.research.google.com/github/pillaiganesh/MyAIAdventures/blob/IITB-Workshop/TensorflowAndKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import keras

Tensor - 0(Constanr, 1D (Vectors), 2D (Marix), 3D or More (Tensors)

In [ ]:
const_1 =tf.constant(100)

In [ ]:
const_1.shape

TensorShape([])

In [ ]:
const_1.numpy()

100

In [ ]:
const_2 = tf.constant([10,20,30,40,50,60,70,80])

In [ ]:
const_2.shape

TensorShape([8])

In [ ]:
const_2.numpy()

array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int32)

In [ ]:
const_3 = tf.constant([[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]])

In [ ]:
const_3.shape

TensorShape([3, 7])

In [ ]:
const_3.numpy()

array([[10, 20, 30, 40, 50, 60, 70],
       [10, 20, 30, 40, 50, 60, 70],
       [10, 20, 30, 40, 50, 60, 70]], dtype=int32)

In [ ]:
const_4 = tf.constant([
                      [[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]],

                      [[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]],
                       ])

In [ ]:
const_4.shape

TensorShape([2, 3, 7])

In [ ]:
# This is N-Dimensional representation of an Numpy Array representing various Ranks like:
# scalar : rank = 0, vector : rank = 1, matrix : rank = 2, tensor : 3 or more.

In [ ]:
const_4.numpy()

array([[[10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70]],

       [[10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70]]], dtype=int32)

##### Mathematical operations

In [21]:
X = tf.constant([[8],
                 [9],
                 [11],
                 [7],
                 [10],
                 [12]])

In [22]:
X.shape

TensorShape([6, 1])

In [23]:
W = tf.Variable([[10],
                 [11],
                 [12],
                 [13],
                 [14],
                 [15]])
W.shape

TensorShape([6, 1])

In [28]:
# Y = XT * W + bias
# or
# Y = X * WT + bias
WT = tf.transpose(W)
tf.tensordot(WT, X, axes = 1)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[722]], dtype=int32)>

In [31]:
tf.tensordot(X, WT, axes = 1)

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[ 80,  88,  96, 104, 112, 120],
       [ 90,  99, 108, 117, 126, 135],
       [110, 121, 132, 143, 154, 165],
       [ 70,  77,  84,  91,  98, 105],
       [100, 110, 120, 130, 140, 150],
       [120, 132, 144, 156, 168, 180]], dtype=int32)>

##### Keras:
Keras is high level API based on Tensorflow, to create Deep Learning Neural Networks easily.
(Dense Neural Network (DNN), CNN & RNN